name: Execute Notebook

on: [push, pull_request]

jobs:
  build:
    if: "contains(github.event.pull_request.title, '[execnb]') || contains(github.event.head_commit.message, '[execnb]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code
        run: |
          cd notebook
          jupyter nbconvert --to notebook --execute inkovis_nb.ipynb --inplace

      - name: Commit Changes
        run: |
          git config --global user.email "${GH_EMAIL}"
          git config --global user.name "${GH_USERNAME}"
          git add -A
          git commit -m '[GHA] EXECUTE NOTEBOOK'
          git push
        env:
          GH_EMAIL: ${{ github.event.commits[0].author.email }}
          GH_USERNAME: ${{ github.event.commits[0].author.username }}
