name: Update Dataset

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    # if: "contains(github.event.pull_request.title, '[execnb]') || contains(github.event.head_commit.message, '[execnb]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-actions.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-actions.txt

      - name: Run code
        run: |
          python auto_update.py

      - name: Commit Changes
        run: |
          git config --global user.email "hi@taruma.info"
          git config --global user.name "taruma"
          git add -A
          git commit -m 'Actions: Update Dataset [execnb]'
          git push
