name: Update Dataset

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    # if: "contains(github.event.pull_request.title, '[execnb]') || contains(github.event.head_commit.message, '[execnb]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-actions.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-actions.txt
          pip install kaggle==1.5.4

      - name: Run code
        run: |
          python auto_update.py

      - name: Commit Changes
        run: |
          git config --global user.email "timhidrokit@gmail.com"
          git config --global user.name "hidrokit"
          git add -A
          git commit -m 'Actions: Update Dataset'
          git push

      - name: Kaggle Update
        run: |
          mkdir kaggle
          cd kaggle
          echo "DOWNLOAD METADATA AND FILES"
          kaggle datasets download ${KAGGLE_DATASET_URL} --unzip
          kaggle datasets metadata ${KAGGLE_DATASET_URL}
          echo "COPY NEW DATASET"
          cp ../dataset/data_infeksi_covid19_indonesia.csv ./data_infeksi_covid19_indonesia.csv
          echo "UPLOAD DATASET"
          kaggle datasets version -m "updated data [hidrokit/inkovis]"
          echo "FINISH"
          ls -l
        env:
          KAGGLE_DATASET_URL: ${{ secrets.KAGGLE_DATASET_URL }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
